defaults:
  - paths: paths

paths:
  cache_dir: /net/tscratch/people/plgmaciejstranz/cache
  data_file: /net/tscratch/people/plgmaciejstranz/all-data.csv
  output_dir: ./results
  logs_dir: ./logs
  trained_model_dir: trained_weights_fine_testowy_3po

training:
  num_train_epochs: 1
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 8
  gradient_accumulation_steps: 4
  warmup_steps: 500
  evaluation_strategy: epoch
  logging_steps: 25
  save_steps: 0
  report_to: tensorboard

model:
  name: TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T